In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 
import warnings
warnings.filterwarnings(action='ignore')

## 1) 장타율 예측

df1,2 중 RMSE가 가장 낮은 모델 3개 평균

+

df3 중 RMSE가 가장 낮은 모델 3개 평균

+

2021년 OPS

+

9/14

#### 1번 (전체 시즌 평균)


df3 사용 
Linear Regression, Random Forest, XGBoost

모델 3개 예측값 평균


장타율 = Linear Regression

In [ ]:
df3 = pd.read_csv('/content/drive/MyDrive/빅콘테스트/Train_dataset/1번/df3.csv', index_col=0)
df3

PCODE       타율     홈런  인플레이타구비율    뜬공땅볼비율      배럴지수      장타율
3    50165  0.26050  23.00  0.307494  2.253521  0.157248  0.50700
11   50350  0.25400   2.00  0.297030  1.897436  0.062500  0.33600
14   50458  0.24950   1.00  0.290960  1.112360  0.000000  0.29300
15   50468  0.28000   6.00  0.369048  1.625000  0.108434  0.47700
16   50469  0.20900   8.00  0.259843  1.629630  0.078261  0.36700
..     ...      ...    ...       ...       ...       ...      ...
428  79402  0.26225   5.25  0.307811  1.334507  0.022989  0.34375
430  79456  0.30200   0.75  0.337224  0.790816  0.004754  0.35425
433  79608  0.31700  10.25  0.344578  1.822034  0.039496  0.46725
435  99606  0.29500   4.00  0.387597  1.074074  0.042017  0.42100
436  99810  0.31800   3.00  0.359504  1.142857  0.036697  0.41700

[143 rows x 7 columns]

In [ ]:
from sklearn.model_selection import train_test_split

#linear regression
x = df3[['타율','홈런','인플레이타구비율','뜬공땅볼비율','배럴지수']]
y = df3[['장타율']]
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2)

In [ ]:
# 칼럼별 분포를 정규화 시켜줄 필요성 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test= scaler.transform(x_test)

In [ ]:
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()
lr_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred = lr_model.predict(x_test)

In [ ]:
df3_test = pd.read_csv('/content/drive/MyDrive/빅콘테스트/Train_dataset/1번/df3_test.csv', index_col=0)
df3_test

PCODE       타율     홈런  인플레이타구비율    뜬공땅볼비율      배럴지수      장타율
372  76232  0.34700  24.00  0.346276  2.455882  0.092649  0.60650
262  68050  0.33775  18.75  0.382602  1.640000  0.095482  0.53550
369  75847  0.27625  29.25  0.296059  3.041176  0.119007  0.55050
245  67341  0.34225   7.50  0.368867  1.720395  0.033686  0.49000
416  79192  0.31375  16.00  0.353955  1.683333  0.101105  0.49175
398  78224  0.28850  26.25  0.349153  1.596639  0.145780  0.52325
402  78513  0.31250  21.25  0.328302  1.517685  0.084567  0.50050
375  76290  0.32125  16.25  0.343522  1.537705  0.095029  0.50425
418  79215  0.32175   9.50  0.356465  1.893878  0.089202  0.46125
257  67872  0.27850  30.50  0.313156  2.399061  0.105556  0.52750

In [ ]:
df3_x_test = df3_test[['타율','홈런','인플레이타구비율','뜬공땅볼비율','배럴지수']]
df3_x_test = x_test= scaler.transform(df3_x_test)

In [ ]:
df3_test_lr = lr_model.predict(df3_x_test)
df3_test_lr

array([[0.58837749],
       [0.54748118],
       [0.55112142],
       [0.46833586],
       [0.51638107],
       [0.55712598],
       [0.52833319],
       [0.52403716],
       [0.49278197],
       [0.5433752 ]])

장타율 - RandomForest

In [ ]:
x = df3[['타율','홈런','인플레이타구비율','뜬공땅볼비율','배럴지수']]
y = df3[['장타율']]
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2)

In [ ]:
rf_model = RandomForestRegressor(max_depth=5, n_estimators = 100, 
                                 min_samples_leaf=2, min_samples_split = 3, 
                                 bootstrap=True, random_state=0)

rf_model.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=5, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=2,
                      min_samples_split=3, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [ ]:
df3_test = pd.read_csv('/content/drive/MyDrive/빅콘테스트/Train_dataset/1번/df3_test.csv', index_col=0)
df3_x_test = df3_test[['타율','홈런','인플레이타구비율','뜬공땅볼비율','배럴지수']]
df3_x_test

타율     홈런  인플레이타구비율    뜬공땅볼비율      배럴지수
372  0.34700  24.00  0.346276  2.455882  0.092649
262  0.33775  18.75  0.382602  1.640000  0.095482
369  0.27625  29.25  0.296059  3.041176  0.119007
245  0.34225   7.50  0.368867  1.720395  0.033686
416  0.31375  16.00  0.353955  1.683333  0.101105
398  0.28850  26.25  0.349153  1.596639  0.145780
402  0.31250  21.25  0.328302  1.517685  0.084567
375  0.32125  16.25  0.343522  1.537705  0.095029
418  0.32175   9.50  0.356465  1.893878  0.089202
257  0.27850  30.50  0.313156  2.399061  0.105556

In [ ]:
df3_test_rf = rf_model.predict(df3_x_test)
df3_test_rf

array([0.57767228, 0.55759904, 0.51569175, 0.44511387, 0.4823849 ,
       0.53210468, 0.56353394, 0.48794398, 0.46420736, 0.50152073])

장타율 - XGBoost

In [ ]:
x = df3[['타율','홈런','인플레이타구비율','뜬공땅볼비율','배럴지수']]
y = df3[['장타율']]
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2)

In [ ]:
import xgboost

xgb_model = xgboost.XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.75, gamma=0,
             importance_type='gain', learning_rate=0.02, max_delta_step=0,
             max_depth=7, min_child_weight=1, missing=None, n_estimators=1000,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0.03, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)
xgb_model.fit(x_train,y_train)

[12:05:37] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.75, gamma=0,
             importance_type='gain', learning_rate=0.02, max_delta_step=0,
             max_depth=7, min_child_weight=1, missing=None, n_estimators=1000,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0.03, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [ ]:
df3_test_xgb = xgb_model.predict(df3_x_test)
df3_test_xgb

array([0.50899404, 0.5147848 , 0.5077991 , 0.4585406 , 0.5005234 ,
       0.5164686 , 0.5195724 , 0.4767856 , 0.4697238 , 0.49102458],
      dtype=float32)

In [ ]:
df3_test_lr = np.array(df3_test_lr).flatten()
df3_test_lr

array([0.5883775 , 0.5474812 , 0.5511214 , 0.46833587, 0.5163811 ,
       0.557126  , 0.5283332 , 0.5240372 , 0.49278197, 0.5433752 ],
      dtype=float32)

In [ ]:
df3_test_rf = df3_test_rf.astype(np.float32)
df3_test_rf

array([0.5776723 , 0.55759907, 0.51569176, 0.44511387, 0.4823849 ,
       0.5321047 , 0.56353396, 0.48794398, 0.46420735, 0.50152075],
      dtype=float32)

In [ ]:
df3_test_xgb

array([0.50899404, 0.5147848 , 0.5077991 , 0.4585406 , 0.5005234 ,
       0.5164686 , 0.5195724 , 0.4767856 , 0.4697238 , 0.49102458],
      dtype=float32)

In [ ]:
slg1 = (df3_test_lr + df3_test_rf + df3_test_xgb) / 3
slg1

array([0.55834794, 0.539955  , 0.5248708 , 0.4573301 , 0.4997631 ,
       0.5352331 , 0.5371465 , 0.49625555, 0.47557104, 0.5119735 ],
      dtype=float32)

#### 2번 (연도별 가중치 평균)

df3 사용 Linear Regression, RandomForest, XGBoost
모델 3개 예측값 평균

In [ ]:
df6 = pd.read_csv('/content/drive/MyDrive/빅콘테스트/Train_dataset/2번/df3.csv', index_col=0)
df6

PCODE       타율     홈런  인플레이타구비율    뜬공땅볼비율      배럴지수      장타율
3    50165  0.26050  23.00  0.307494  2.239521  0.182801  0.50700
11   50350  0.25400   2.00  0.297030  1.897436  0.068750  0.33600
14   50458  0.24950   1.00  0.290960  1.101408  0.000000  0.29300
15   50468  0.28000   6.00  0.369048  1.625000  0.119277  0.47700
16   50469  0.20900   8.00  0.259843  1.629630  0.086087  0.36700
..     ...      ...    ...       ...       ...       ...      ...
428  79402  0.26225   5.25  0.307811  1.346857  0.021220  0.34375
430  79456  0.30200   0.75  0.337224  0.826477  0.003962  0.35425
433  79608  0.31700  10.25  0.344578  1.793256  0.035714  0.46725
435  99606  0.29500   4.00  0.387597  1.074074  0.029412  0.42100
436  99810  0.31800   3.00  0.359504  1.142857  0.025688  0.41700

[143 rows x 7 columns]

장타율 - Linear Regression

In [ ]:
x = df6[['타율','홈런','인플레이타구비율','뜬공땅볼비율','배럴지수']]
y = df6[['장타율']]
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test= scaler.transform(x_test)

In [ ]:
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()
lr_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
df6_test = pd.read_csv('/content/drive/MyDrive/빅콘테스트/Train_dataset/2번/df3_test.csv', index_col = 0)
df6_test

PCODE       타율     홈런  인플레이타구비율    뜬공땅볼비율      배럴지수      장타율
372  76232  0.34700  24.00  0.346276  2.512333  0.090429  0.60650
262  68050  0.33775  18.75  0.382602  1.656646  0.090367  0.53550
369  75847  0.27625  29.25  0.296059  3.029412  0.115154  0.55050
245  67341  0.34225   7.50  0.368867  1.747616  0.034280  0.49000
416  79192  0.31375  16.00  0.353955  1.732507  0.095752  0.49175
398  78224  0.28850  26.25  0.349153  1.586055  0.139557  0.52325
402  78513  0.31250  21.25  0.328302  1.553327  0.080761  0.50050
375  76290  0.32125  16.25  0.343522  1.583758  0.094591  0.50425
418  79215  0.32175   9.50  0.356465  1.957112  0.086541  0.46125
257  67872  0.27850  30.50  0.313156  2.391977  0.102302  0.52750

In [ ]:
df6_test = df6_test[['타율','홈런','인플레이타구비율','뜬공땅볼비율','배럴지수']]
df6_test = scaler.fit_transform(df6_test)

In [ ]:
df6_test_lr = lr_model.predict(df6_test)
df6_test_lr

array([[0.47302147],
       [0.42162859],
       [0.41143011],
       [0.33598431],
       [0.3808349 ],
       [0.41991057],
       [0.39188163],
       [0.39479052],
       [0.35987733],
       [0.4011815 ]])

장타율 - RandomForest

In [ ]:
x = df6[['타율','홈런','인플레이타구비율','뜬공땅볼비율','배럴지수']]
y = df6[['장타율']]
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2)

In [ ]:
rf_model = RandomForestRegressor(max_depth=6, n_estimators = 100, min_samples_leaf=2, min_samples_split = 2, bootstrap=True, random_state=0)

rf_model.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=6, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=2,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [ ]:
df6_test = pd.read_csv('/content/drive/MyDrive/빅콘테스트/Train_dataset/2번/df3_test.csv', index_col = 0)
df6_test = df6_test[['타율','홈런','인플레이타구비율','뜬공땅볼비율','배럴지수']]

In [ ]:
df6_test_rf = rf_model.predict(df6_test)
df6_test_rf

array([0.54583108, 0.53326571, 0.53107061, 0.43464688, 0.47852914,
       0.53209853, 0.53085015, 0.47818684, 0.44936046, 0.53270857])

In [ ]:
x = df6[['타율','홈런','인플레이타구비율','뜬공땅볼비율','배럴지수']]
y = df6[['장타율']]
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2)

In [ ]:
xgb_model = xgboost.XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.75, gamma=0,
             importance_type='gain', learning_rate=0.02, max_delta_step=0,
             max_depth=7, min_child_weight=1, missing=None, n_estimators=1000,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0.03, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)
xgb_model.fit(x_train,y_train)

[12:29:55] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.75, gamma=0,
             importance_type='gain', learning_rate=0.02, max_delta_step=0,
             max_depth=7, min_child_weight=1, missing=None, n_estimators=1000,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0.03, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [ ]:
df6_test_xgb = xgb_model.predict(df6_test)
df6_test_xgb

array([0.55344313, 0.51930195, 0.5162652 , 0.46641502, 0.5031612 ,
       0.52902853, 0.5416157 , 0.49011928, 0.48254287, 0.54582655],
      dtype=float32)

In [ ]:
df6_test_lr = np.array(df6_test_lr).flatten()
df6_test_lr

array([0.47302147, 0.42162859, 0.41143011, 0.33598431, 0.3808349 ,
       0.41991057, 0.39188163, 0.39479052, 0.35987733, 0.4011815 ])

In [ ]:
df6_test_rf = df6_test_rf.astype(np.float32)
df6_test_rf

array([0.5458311 , 0.5332657 , 0.5310706 , 0.43464687, 0.47852913,
       0.53209853, 0.5308502 , 0.47818685, 0.44936046, 0.5327086 ],
      dtype=float32)

In [ ]:
slg2 = (df6_test_lr + df6_test_rf + df6_test_xgb)/3
slg2

array([0.52409856, 0.49139875, 0.4862553 , 0.41234874, 0.45417507,
       0.49367921, 0.48811584, 0.45436555, 0.43059356, 0.49323888])

#### 3번 (시즌별로 따로 집계)

df3 사용 Linear Regression, RandomForest, XGBoost 모델 3개 예측값 평균

In [ ]:
df9 = pd.read_csv('/content/drive/MyDrive/빅콘테스트/Train_dataset/3번/df3.csv', index_col=0)
df9

PCODE_YEAR     타율  홈런  인플레이타구비율    뜬공땅볼비율      배럴지수    장타율
0    50165_2020  0.278  38  0.324111  2.386364  0.160584  0.592
1    50165_2021  0.243   8  0.276119  2.037037  0.150376  0.422
2    50350_2020  0.254   2  0.297030  1.897436  0.062500  0.336
3    50458_2020  0.232   1  0.280193  1.239130  0.000000  0.272
4    50458_2021  0.267   1  0.306122  0.976744  0.000000  0.314
..          ...    ...  ..       ...       ...       ...    ...
461  79608_2019  0.315   5  0.346032  1.666667  0.020619  0.412
462  79608_2020  0.286   8  0.309859  2.203390  0.028571  0.413
463  79608_2021  0.325   5  0.376471  1.268293  0.048193  0.481
464  99606_2018  0.295   4  0.387597  1.074074  0.042017  0.421
465  99810_2018  0.318   3  0.359504  1.142857  0.036697  0.417

[456 rows x 7 columns]

장타율 - Linear Regression

In [ ]:
x = df9[['타율','홈런','인플레이타구비율','뜬공땅볼비율','배럴지수']]
y = df9[['장타율']]
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2)

In [ ]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test= scaler.transform(x_test)

In [ ]:
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()
lr_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
df9_test = pd.read_csv('/content/drive/MyDrive/빅콘테스트/Train_dataset/3번/df3_test.csv', index_col = 0)
df9_test 

PCODE_YEAR     타율  홈런  인플레이타구비율    뜬공땅볼비율      배럴지수    장타율
343  76232_2021  0.348  20  0.341837  3.000000  0.105769  0.664
220  68050_2021  0.395  10  0.455399  1.928571  0.079365  0.579
337  75847_2021  0.299  20  0.320988  2.620690  0.114754  0.598
201  67341_2021  0.345   3  0.372180  1.258621  0.028455  0.503
435  79192_2021  0.316  12  0.353293  2.129032  0.110465  0.533
401  78224_2021  0.271  16  0.307692  1.562500  0.166667  0.508
409  78513_2021  0.328   4  0.365079  1.863636  0.062222  0.447
354  76290_2021  0.288  12  0.290179  1.695652  0.131068  0.468
439  79215_2021  0.338   2  0.396648  2.192308  0.049689  0.435
214  67872_2021  0.240  18  0.247475  1.840909  0.105000  0.459

In [ ]:
df9_test  = df9_test [['타율','홈런','인플레이타구비율','뜬공땅볼비율','배럴지수']]
df9_test = scaler.fit_transform(df9_test)

In [ ]:
df9_test_lr = lr_model.predict(df9_test)
df9_test_lr

array([[0.50198291],
       [0.46916383],
       [0.45578272],
       [0.34233661],
       [0.42262075],
       [0.43053858],
       [0.35794401],
       [0.40376794],
       [0.35215386],
       [0.37274725]])

장타율 - RandomForest

In [ ]:
x = df9[['타율','홈런','인플레이타구비율','뜬공땅볼비율','배럴지수']]
y = df9[['장타율']]
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2)

In [ ]:
rf_model = RandomForestRegressor(max_depth=6, n_estimators = 200, min_samples_leaf=1, min_samples_split = 2, bootstrap=True, random_state=0)

rf_model.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=6, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=200, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [ ]:
df9_test = pd.read_csv('/content/drive/MyDrive/빅콘테스트/Train_dataset/3번/df3_test.csv', index_col = 0)
df9_test  = df9_test [['타율','홈런','인플레이타구비율','뜬공땅볼비율','배럴지수']]
df9_test 

타율  홈런  인플레이타구비율    뜬공땅볼비율      배럴지수
343  0.348  20  0.341837  3.000000  0.105769
220  0.395  10  0.455399  1.928571  0.079365
337  0.299  20  0.320988  2.620690  0.114754
201  0.345   3  0.372180  1.258621  0.028455
435  0.316  12  0.353293  2.129032  0.110465
401  0.271  16  0.307692  1.562500  0.166667
409  0.328   4  0.365079  1.863636  0.062222
354  0.288  12  0.290179  1.695652  0.131068
439  0.338   2  0.396648  2.192308  0.049689
214  0.240  18  0.247475  1.840909  0.105000

In [ ]:
df9_test_rf = rf_model.predict(df9_test)
df9_test_rf

array([0.52481898, 0.48372813, 0.50334632, 0.42641383, 0.4675185 ,
       0.48880645, 0.44665525, 0.45724103, 0.43281608, 0.45870595])

In [ ]:
x = df9[['타율','홈런','인플레이타구비율','뜬공땅볼비율','배럴지수']]
y = df9[['장타율']]
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2)

In [ ]:
xgb_model = xgboost.XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.75, gamma=0,
             importance_type='gain', learning_rate=0.02, max_delta_step=0,
             max_depth=7, min_child_weight=1, missing=None, n_estimators=1000,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0.03, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)
xgb_model.fit(x_train,y_train)

[12:44:04] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.75, gamma=0,
             importance_type='gain', learning_rate=0.02, max_delta_step=0,
             max_depth=7, min_child_weight=1, missing=None, n_estimators=1000,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0.03, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [ ]:
df9_test_xgb = xgb_model.predict(df9_test)
df9_test_xgb

array([0.54727525, 0.51308984, 0.5029077 , 0.43950003, 0.47845495,
       0.48552144, 0.45784366, 0.4786193 , 0.45502716, 0.4571775 ],
      dtype=float32)

In [ ]:
df9_test_lr = np.array(df9_test_lr).flatten()
df9_test_lr

array([0.50198291, 0.46916383, 0.45578272, 0.34233661, 0.42262075,
       0.43053858, 0.35794401, 0.40376794, 0.35215386, 0.37274725])

In [ ]:
df9_test_rf = df9_test_rf.astype(np.float32)
df9_test_rf

array([0.52481896, 0.48372814, 0.5033463 , 0.42641383, 0.4675185 ,
       0.48880646, 0.44665524, 0.45724103, 0.4328161 , 0.45870596],
      dtype=float32)

In [ ]:
slg3 = (df9_test_lr + df9_test_rf + df9_test_xgb) / 3
slg3

array([0.52469237, 0.4886606 , 0.48734558, 0.40275016, 0.45619807,
       0.46828882, 0.4208143 , 0.44654276, 0.41333237, 0.42954357])

#### 4번(21년 시즌 해당 선수 기록 평균값)

In [ ]:
slg4 = pd.read_excel('/content/drive/MyDrive/빅콘테스트/Train_dataset/21년과최근30일.xlsx',index_col=0)
slg4

NAME  21출루율  21장타율  21OPS  30일출루율  30일장타율  30일OPS
PCODE                                                  
76232  양의지  0.429  0.612  1.041   0.341   0.430   0.771
68050  강백호  0.467  0.577  1.044   0.344   0.573   0.917
75847   최정  0.410  0.584  0.994   0.368   0.623   0.991
67341  이정후  0.449  0.525  0.973   0.609   0.857   1.466
79192  채은성  0.372  0.522  0.894   0.250   0.417   0.667
78224  김재환  0.389  0.505  0.893   0.344   0.471   0.814
78513  전준우  0.380  0.424  0.805   0.280   0.372   0.652
76290  김현수  0.376  0.460  0.836   0.381   0.452   0.833
79215  박건우  0.407  0.439  0.847   0.422   0.465   0.887
67872   로맥  0.348  0.431  0.778   0.260   0.295   0.556

In [ ]:
slg4 = slg4['21장타율']
slg4

PCODE
76232    0.612
68050    0.577
75847    0.584
67341    0.525
79192    0.522
78224    0.505
78513    0.424
76290    0.460
79215    0.439
67872    0.431
Name: 21장타율, dtype: float64

#### 5번(최근 30경기 해당 선수 기록 평균값)

In [ ]:
slg5 = pd.read_excel('/content/drive/MyDrive/빅콘테스트/Train_dataset/21년과최근30일.xlsx',index_col=0)
slg5 = slg5['30일장타율']
slg5

PCODE
76232    0.430
68050    0.573
75847    0.623
67341    0.857
79192    0.417
78224    0.471
78513    0.372
76290    0.452
79215    0.465
67872    0.295
Name: 30일장타율, dtype: float64

#### 최종 장타율 예측

In [ ]:
slg1

array([0.55834794, 0.539955  , 0.5248708 , 0.4573301 , 0.4997631 ,
       0.5352331 , 0.5371465 , 0.49625555, 0.47557104, 0.5119735 ],
      dtype=float32)

In [ ]:
slg2

array([0.52409856, 0.49139875, 0.4862553 , 0.41234874, 0.45417507,
       0.49367921, 0.48811584, 0.45436555, 0.43059356, 0.49323888])

In [ ]:
slg3

array([0.52469237, 0.4886606 , 0.48734558, 0.40275016, 0.45619807,
       0.46828882, 0.4208143 , 0.44654276, 0.41333237, 0.42954357])

In [ ]:
slg4

PCODE
76232    0.612
68050    0.577
75847    0.584
67341    0.525
79192    0.522
78224    0.505
78513    0.424
76290    0.460
79215    0.439
67872    0.431
Name: 21장타율, dtype: float64

In [ ]:
slg5

PCODE
76232    0.430
68050    0.573
75847    0.623
67341    0.857
79192    0.417
78224    0.471
78513    0.372
76290    0.452
79215    0.465
67872    0.295
Name: 30일장타율, dtype: float64

In [ ]:
slg = (slg1 + slg2 + slg3 + slg4 + slg5)/5
slg

PCODE
76232    0.529828
68050    0.534003
75847    0.541094
67341    0.530886
79192    0.469827
78224    0.494640
78513    0.448415
76290    0.461833
79215    0.444699
67872    0.432151
dtype: float64

## 2) 출루율 예측

1번 - df2 / LR, RF, XGB

2번 - df1 / LR, RF, XGB

3번 - df1 / LR, RF, XGB

#### 1번 (전체 시즌 평균)

In [ ]:
df2 = pd.read_csv('/content/drive/MyDrive/빅콘테스트/Train_dataset/출루율/1번/df2.csv', index_col=0)
df2

PCODE        타율         홈런       볼삼비  ...      전체     컨택%  2S후선구%       출루율
0    74540  0.278500  16.250000  0.451362  ...  45.275  77.725  36.825  0.345431
2    62925  0.263250   4.500000  0.387931  ...  47.050  85.450  26.400  0.337010
3    61353  0.285000   3.000000  0.215686  ...  52.850  76.050  30.300  0.327765
4    62404  0.296750  15.250000  0.470930  ...  47.825  78.075  32.850  0.366544
5    63963  0.265500   8.500000  0.803738  ...  40.675  86.200  36.575  0.370317
..     ...       ...        ...       ...  ...     ...     ...     ...       ...
121  79240  0.316750   6.250000  0.881481  ...  43.375  89.325  31.200  0.370721
122  68730  0.261333  17.333333  0.451613  ...  47.700  78.350  35.000  0.352336
123  66108  0.258500   2.000000  1.006623  ...  36.800  84.050  42.350  0.433815
124  76313  0.301500  18.250000  0.524691  ...  44.175  80.700  34.225  0.366316
125  51725  0.257000   7.000000  0.275862  ...  46.700  75.700  27.500  0.305970

[116 rows x 9 columns]

In [ ]:
#linear regression
x = df2[['타율','홈런','볼삼비','P/PA','전체','컨택%','2S후선구%']]
y = df2[['출루율']]
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2)

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test= scaler.transform(x_test)

lr_model = LinearRegression()
lr_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
df2_test = pd.read_csv('/content/drive/MyDrive/빅콘테스트/Train_dataset/출루율/1번/df2_test.csv', index_col=0)
df2_test

PCODE       타율     홈런       볼삼비    P/PA      전체     컨택%  2S후선구%       출루율
70   76232  0.34700  24.00  1.131250  3.6875  45.150  89.150  33.125  0.431806
1    68050  0.33775  18.75  0.670487  4.0000  44.225  78.775  37.525  0.415301
111  75847  0.27625  29.25  0.662198  3.9850  47.100  75.475  38.475  0.397044
87   67341  0.34225   7.50  1.179641  3.7950  38.575  91.750  34.475  0.407529
106  79192  0.31375  16.00  0.410909  3.7350  49.700  79.500  30.475  0.367841
17   78224  0.28850  26.25  0.563715  3.8475  47.625  69.750  41.600  0.386711
97   78513  0.31250  21.25  0.712121  3.7075  43.600  84.100  36.375  0.376540
25   76290  0.32125  16.25  1.067708  3.7225  44.200  86.900  34.950  0.398547
42   79215  0.32175   9.50  0.703196  3.6950  45.225  84.025  32.450  0.384202
36   67872  0.27850  30.50  0.692308  4.1150  43.075  76.125  40.250  0.389045

In [ ]:
df2_test = df2_test[['타율','홈런','볼삼비','P/PA','전체','컨택%','2S후선구%']]
df2_test = scaler.fit_transform(df2_test)

In [ ]:
df2_test_lr = lr_model.predict(df2_test)
df2_test_lr

array([[0.37304481],
       [0.371318  ],
       [0.32960843],
       [0.38133993],
       [0.31243187],
       [0.3389814 ],
       [0.34162751],
       [0.35781627],
       [0.33538387],
       [0.34528996]])

In [ ]:
df2_test_lr = np.array(df2_test_lr).flatten()
df2_test_lr

array([0.37304481, 0.371318  , 0.32960843, 0.38133993, 0.31243187,
       0.3389814 , 0.34162751, 0.35781627, 0.33538387, 0.34528996])

In [ ]:
x = df2[['타율','홈런','볼삼비','P/PA','전체','컨택%','2S후선구%']]
y = df2[['출루율']]
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2)

In [ ]:
rf_model = RandomForestRegressor(max_depth=6, n_estimators = 100, min_samples_leaf=2, min_samples_split = 4, bootstrap=True, random_state=0)

rf_model.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=6, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=2,
                      min_samples_split=4, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [ ]:
df2_test = pd.read_csv('/content/drive/MyDrive/빅콘테스트/Train_dataset/출루율/1번/df2_test.csv', index_col=0)
df2_test = df2_test[['타율','홈런','볼삼비','P/PA','전체','컨택%','2S후선구%']]
df2_test

타율     홈런       볼삼비    P/PA      전체     컨택%  2S후선구%
70   0.34700  24.00  1.131250  3.6875  45.150  89.150  33.125
1    0.33775  18.75  0.670487  4.0000  44.225  78.775  37.525
111  0.27625  29.25  0.662198  3.9850  47.100  75.475  38.475
87   0.34225   7.50  1.179641  3.7950  38.575  91.750  34.475
106  0.31375  16.00  0.410909  3.7350  49.700  79.500  30.475
17   0.28850  26.25  0.563715  3.8475  47.625  69.750  41.600
97   0.31250  21.25  0.712121  3.7075  43.600  84.100  36.375
25   0.32125  16.25  1.067708  3.7225  44.200  86.900  34.950
42   0.32175   9.50  0.703196  3.6950  45.225  84.025  32.450
36   0.27850  30.50  0.692308  4.1150  43.075  76.125  40.250

In [ ]:
df2_test_rf = rf_model.predict(df2_test)
df2_test_rf = df2_test_rf.astype(np.float32)
df2_test_rf

array([0.38807636, 0.39742452, 0.38050398, 0.38997224, 0.36484882,
       0.38290042, 0.39163402, 0.39203754, 0.37542972, 0.38355723],
      dtype=float32)

In [ ]:
xgb_model = xgboost.XGBRegressor(n_estimators=100, learning_rate=0.08, gamma=0, subsample=0.75,
                           colsample_bytree=1, max_depth=7)
xgb_model.fit(x_train,y_train)

[13:45:30] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.08, max_delta_step=0,
             max_depth=7, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=0.75, verbosity=1)

In [ ]:
df2_test_xgb = xgb_model.predict(df2_test)
df2_test_xgb

array([0.40124115, 0.39872655, 0.39642924, 0.40360212, 0.36498317,
       0.3934558 , 0.3864321 , 0.38849363, 0.37857956, 0.39725322],
      dtype=float32)

In [ ]:
obp1 = (df2_test_lr + df2_test_rf + df2_test_xgb)/3
obp1

array([0.38745411, 0.38915636, 0.36884722, 0.3916381 , 0.34742129,
       0.37177921, 0.37323121, 0.37944915, 0.36313105, 0.3753668 ])

#### 2번 (연도별 가중치 평균)

In [ ]:
df4 = pd.read_csv('/content/drive/MyDrive/빅콘테스트/Train_dataset/출루율/2번/df1.csv', index_col=0)

x = df4[['타율','홈런','볼삼비','P/PA','초구','전체','컨택%','2S후커트%','2S후선구%']]
y = df4[['출루율']]
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2)

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test= scaler.transform(x_test)

lr_model = LinearRegression()
lr_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
df4_test = pd.read_csv('/content/drive/MyDrive/빅콘테스트/Train_dataset/출루율/2번/df1_test.csv',index_col=0)
df4_test

PCODE        타율      홈런       볼삼비  ...      컨택%   2S후커트%   2S후선구%       출루율
91   76232  0.345600  24.100  1.142948  ...  88.9600  84.9250  32.7775  0.431669
3    68050  0.345475  17.575  0.722307  ...  79.0825  75.2475  37.3975  0.425245
146  75847  0.279825  28.225  0.694104  ...  75.8975  74.4375  38.4475  0.400284
114  67341  0.341425   7.500  1.281708  ...  91.8950  87.4050  34.8325  0.409251
140  79192  0.312075  15.100  0.424816  ...  79.2450  78.5475  30.3475  0.367242
25   78224  0.283350  24.525  0.584736  ...  69.1950  63.4025  42.0600  0.385457
130  78513  0.310900  19.175  0.747798  ...  84.0850  79.7325  36.3025  0.375882
34   76290  0.316375  15.925  1.123899  ...  87.0750  85.1450  34.8500  0.396961
53   79215  0.322275   8.850  0.719390  ...  83.9125  79.9200  32.6800  0.385204
45   67872  0.272950  28.700  0.714861  ...  76.1975  73.2800  40.2200  0.387243

[10 rows x 11 columns]

In [ ]:
df4_test = df4_test[['타율','홈런','볼삼비','P/PA','초구','전체','컨택%','2S후커트%','2S후선구%']]
df4_test = scaler.fit_transform(df4_test)

In [ ]:
df4_test_lr = lr_model.predict(df4_test)
df4_test_lr = np.array(df4_test_lr).flatten()
df4_test_lr

array([0.3656144 , 0.42580535, 0.32367945, 0.39418745, 0.29415195,
       0.34663864, 0.31671305, 0.33621833, 0.32615616, 0.34930862])

In [ ]:
x = df4[['타율','홈런','볼삼비','P/PA','초구','전체','컨택%','2S후커트%','2S후선구%']]
y = df4[['출루율']]
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2)

In [ ]:
rf_model = RandomForestRegressor(max_depth=5, n_estimators = 150, min_samples_leaf=2, min_samples_split = 2, bootstrap=True, random_state=0)

rf_model.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=5, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=2,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=150, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [ ]:
df4_test = pd.read_csv('/content/drive/MyDrive/빅콘테스트/Train_dataset/출루율/2번/df1_test.csv',index_col=0)
df4_test = df4_test[['타율','홈런','볼삼비','P/PA','초구','전체','컨택%','2S후커트%','2S후선구%']]

In [ ]:
df4_test_rf = rf_model.predict(df4_test)
df4_test_rf = df4_test_rf.astype(np.float32)
df4_test_rf

array([0.39345473, 0.37707236, 0.37522388, 0.38944203, 0.33909523,
       0.38359544, 0.3844786 , 0.38860777, 0.35685018, 0.37838545],
      dtype=float32)

In [ ]:
x = df4[['타율','홈런','볼삼비','P/PA','초구','전체','컨택%','2S후커트%','2S후선구%']]
y = df4[['출루율']]
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2)

xgb_model = xgboost.XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.75, gamma=0,
             importance_type='gain', learning_rate=0.02, max_delta_step=0,
             max_depth=7, min_child_weight=1, missing=None, n_estimators=1000,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0.03, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)
xgb_model.fit(x_train,y_train)

[13:54:18] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.75, gamma=0,
             importance_type='gain', learning_rate=0.02, max_delta_step=0,
             max_depth=7, min_child_weight=1, missing=None, n_estimators=1000,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0.03, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [ ]:
df4_test_xgb = xgb_model.predict(df4_test)
df4_test_xgb

array([0.390742  , 0.37994725, 0.38053006, 0.38846037, 0.35314995,
       0.38604742, 0.37533748, 0.3912018 , 0.35604984, 0.3810172 ],
      dtype=float32)

In [ ]:
obp2 = (df4_test_lr + df4_test_rf + df4_test_xgb)/3
obp2

array([0.38327038, 0.39427499, 0.35981113, 0.39069661, 0.32879904,
       0.37209383, 0.35884304, 0.3720093 , 0.34635206, 0.36957043])

#### 3번 (시즌별로 따로 집계)

In [ ]:
df7 = pd.read_csv('/content/drive/MyDrive/빅콘테스트/Train_dataset/출루율/3번/df1.csv', index_col=0)

x = df7[['타율','홈런','볼삼비','P/PA','초구','전체','컨택%','2S후커트%','2S후선구%']]
y = df7[['출루율']]
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2)

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test= scaler.transform(x_test)

lr_model = LinearRegression()
lr_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
df7_test = pd.read_csv('/content/drive/MyDrive/빅콘테스트/Train_dataset/출루율/3번/df1_test.csv', index_col= 0)
df7_test = df7_test[['타율','홈런','볼삼비','P/PA','초구','전체','컨택%','2S후커트%','2S후선구%']]
df7_test = scaler.fit_transform(df7_test)

In [ ]:
df7_test_lr = lr_model.predict(df7_test)
df7_test_lr = np.array(df7_test_lr).flatten()
df7_test_lr

array([0.36847368, 0.42771617, 0.342313  , 0.40014993, 0.32128848,
       0.34007181, 0.34982978, 0.33464433, 0.33867679, 0.31459735])

In [ ]:
x = df7[['타율','홈런','볼삼비','P/PA','초구','전체','컨택%','2S후커트%','2S후선구%']]
y = df7[['출루율']]
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2)

In [ ]:
rf_model = RandomForestRegressor(max_depth=6, n_estimators = 100, min_samples_leaf=2, min_samples_split = 4, bootstrap=True, random_state=0)

rf_model.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=6, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=2,
                      min_samples_split=4, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [ ]:
df7_test = pd.read_csv('/content/drive/MyDrive/빅콘테스트/Train_dataset/출루율/3번/df1_test.csv', index_col= 0)
df7_test = df7_test[['타율','홈런','볼삼비','P/PA','초구','전체','컨택%','2S후커트%','2S후선구%']]
df7_test_rf = rf_model.predict(df7_test)
df7_test_rf = df7_test_rf.astype(np.float32)
df7_test_rf

array([0.41726622, 0.43127564, 0.37399527, 0.41558653, 0.37142354,
       0.3726    , 0.4050736 , 0.36852568, 0.4081458 , 0.34658453],
      dtype=float32)

In [ ]:
x = df7[['타율','홈런','볼삼비','P/PA','초구','전체','컨택%','2S후커트%','2S후선구%']]
y = df7[['출루율']]
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2)

In [ ]:
xgb_model = xgboost.XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.75, gamma=0,
             importance_type='gain', learning_rate=0.02, max_delta_step=0,
             max_depth=7, min_child_weight=1, missing=None, n_estimators=1000,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0.03, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)
xgb_model.fit(x_train,y_train)

[14:01:15] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.75, gamma=0,
             importance_type='gain', learning_rate=0.02, max_delta_step=0,
             max_depth=7, min_child_weight=1, missing=None, n_estimators=1000,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0.03, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [ ]:
df7_test_xgb = xgb_model.predict(df7_test)
df7_test_xgb

array([0.41938218, 0.43907574, 0.3949197 , 0.43351197, 0.37262955,
       0.3919822 , 0.40578482, 0.3747944 , 0.39920047, 0.3709721 ],
      dtype=float32)

In [ ]:
obp3 = (df7_test_lr + df7_test_rf + df7_test_xgb)/3
obp3

array([0.40170736, 0.43268918, 0.37040932, 0.41641614, 0.35511386,
       0.368218  , 0.38689607, 0.35932147, 0.38200768, 0.34405132])

#### 4번 (21년 시즌 해당 선수 기록 평균값)

In [ ]:
obp4 = pd.read_excel('/content/drive/MyDrive/빅콘테스트/Train_dataset/21년과최근30일.xlsx',index_col=0)
obp4

NAME  21출루율  21장타율  21OPS  30일출루율  30일장타율  30일OPS
PCODE                                                  
76232  양의지  0.429  0.612  1.041   0.341   0.430   0.771
68050  강백호  0.467  0.577  1.044   0.344   0.573   0.917
75847   최정  0.410  0.584  0.994   0.368   0.623   0.991
67341  이정후  0.449  0.525  0.973   0.609   0.857   1.466
79192  채은성  0.372  0.522  0.894   0.250   0.417   0.667
78224  김재환  0.389  0.505  0.893   0.344   0.471   0.814
78513  전준우  0.380  0.424  0.805   0.280   0.372   0.652
76290  김현수  0.376  0.460  0.836   0.381   0.452   0.833
79215  박건우  0.407  0.439  0.847   0.422   0.465   0.887
67872   로맥  0.348  0.431  0.778   0.260   0.295   0.556

In [ ]:
obp4 = obp4['21출루율']
obp4

PCODE
76232    0.429
68050    0.467
75847    0.410
67341    0.449
79192    0.372
78224    0.389
78513    0.380
76290    0.376
79215    0.407
67872    0.348
Name: 21출루율, dtype: float64

#### 5번 (최근 30경기 해당 선수 기록 평균값)

In [ ]:
obp5 = pd.read_excel('/content/drive/MyDrive/빅콘테스트/Train_dataset/21년과최근30일.xlsx',index_col=0)
obp5

NAME  21출루율  21장타율  21OPS  30일출루율  30일장타율  30일OPS
PCODE                                                  
76232  양의지  0.429  0.612  1.041   0.341   0.430   0.771
68050  강백호  0.467  0.577  1.044   0.344   0.573   0.917
75847   최정  0.410  0.584  0.994   0.368   0.623   0.991
67341  이정후  0.449  0.525  0.973   0.609   0.857   1.466
79192  채은성  0.372  0.522  0.894   0.250   0.417   0.667
78224  김재환  0.389  0.505  0.893   0.344   0.471   0.814
78513  전준우  0.380  0.424  0.805   0.280   0.372   0.652
76290  김현수  0.376  0.460  0.836   0.381   0.452   0.833
79215  박건우  0.407  0.439  0.847   0.422   0.465   0.887
67872   로맥  0.348  0.431  0.778   0.260   0.295   0.556

In [ ]:
obp5 = obp5['30일출루율']
obp5

PCODE
76232    0.341
68050    0.344
75847    0.368
67341    0.609
79192    0.250
78224    0.344
78513    0.280
76290    0.381
79215    0.422
67872    0.260
Name: 30일출루율, dtype: float64

#### 최종 출루율 예측

In [ ]:
obp1

array([0.38745411, 0.38915636, 0.36884722, 0.3916381 , 0.34742129,
       0.37177921, 0.37323121, 0.37944915, 0.36313105, 0.3753668 ])

In [ ]:
obp2

array([0.38327038, 0.39427499, 0.35981113, 0.39069661, 0.32879904,
       0.37209383, 0.35884304, 0.3720093 , 0.34635206, 0.36957043])

In [ ]:
obp3

array([0.40170736, 0.43268918, 0.37040932, 0.41641614, 0.35511386,
       0.368218  , 0.38689607, 0.35932147, 0.38200768, 0.34405132])

In [ ]:
obp4

PCODE
76232    0.429
68050    0.467
75847    0.410
67341    0.449
79192    0.372
78224    0.389
78513    0.380
76290    0.376
79215    0.407
67872    0.348
Name: 21출루율, dtype: float64

In [ ]:
obp5

PCODE
76232    0.341
68050    0.344
75847    0.368
67341    0.609
79192    0.250
78224    0.344
78513    0.280
76290    0.381
79215    0.422
67872    0.260
Name: 30일출루율, dtype: float64

In [ ]:
obp = (obp1 + obp2 + obp3 + obp4 + obp5) / 5
obp

PCODE
76232    0.388486
68050    0.405424
75847    0.375414
67341    0.451350
79192    0.330667
78224    0.369018
78513    0.355794
76290    0.373556
79215    0.384098
67872    0.339398
dtype: float64

## 3) OPS 예측

In [ ]:
slg

PCODE
76232    0.529828
68050    0.534003
75847    0.541094
67341    0.530886
79192    0.469827
78224    0.494640
78513    0.448415
76290    0.461833
79215    0.444699
67872    0.432151
dtype: float64

In [ ]:
obp

PCODE
76232    0.388486
68050    0.405424
75847    0.375414
67341    0.451350
79192    0.330667
78224    0.369018
78513    0.355794
76290    0.373556
79215    0.384098
67872    0.339398
dtype: float64

In [ ]:
ops = slg + obp
ops

PCODE
76232    0.918314
68050    0.939427
75847    0.916508
67341    0.982236
79192    0.800494
78224    0.863658
78513    0.804209
76290    0.835389
79215    0.828798
67872    0.771549
dtype: float64

In [ ]:
test = pd.read_excel('/content/drive/MyDrive/빅콘테스트/02_평가데이터/2021 빅콘테스트_데이터분석분야_챔피언리그_스포츠테크_평가데이터.xlsx')
test 

NO. PCODE   OPS   장타율    출루율
0          NaN  (예시)  1.09  0.68  0.417
1            1   NaN   NaN   NaN    NaN
2            2   NaN   NaN   NaN    NaN
3            3   NaN   NaN   NaN    NaN
4            4   NaN   NaN   NaN    NaN
5            5   NaN   NaN   NaN    NaN
6            6   NaN   NaN   NaN    NaN
7            7   NaN   NaN   NaN    NaN
8            8   NaN   NaN   NaN    NaN
9            9   NaN   NaN   NaN    NaN
10          10   NaN   NaN   NaN    NaN
11  *설명회 자료 참고   NaN   NaN   NaN    NaN

In [ ]:
test = test.drop([0, 11])
test

NO. PCODE  OPS  장타율  출루율
1    1   NaN  NaN  NaN  NaN
2    2   NaN  NaN  NaN  NaN
3    3   NaN  NaN  NaN  NaN
4    4   NaN  NaN  NaN  NaN
5    5   NaN  NaN  NaN  NaN
6    6   NaN  NaN  NaN  NaN
7    7   NaN  NaN  NaN  NaN
8    8   NaN  NaN  NaN  NaN
9    9   NaN  NaN  NaN  NaN
10  10   NaN  NaN  NaN  NaN

In [ ]:
test['PCODE'] = ops.index
test['OPS'] = ops.values
test['장타율'] = slg.values
test['출루율'] = obp.values
test

NO.  PCODE       OPS       장타율       출루율
1    1  76232  0.918314  0.529828  0.388486
2    2  68050  0.939427  0.534003  0.405424
3    3  75847  0.916508  0.541094  0.375414
4    4  67341  0.982236  0.530886  0.451350
5    5  79192  0.800494  0.469827  0.330667
6    6  78224  0.863658  0.494640  0.369018
7    7  78513  0.804209  0.448415  0.355794
8    8  76290  0.835389  0.461833  0.373556
9    9  79215  0.828798  0.444699  0.384098
10  10  67872  0.771549  0.432151  0.339398

In [ ]:
test.to_csv('/content/drive/MyDrive/빅콘테스트/02_평가데이터/최종제출.csv')

In [ ]:
!pip install openpyxl
!pip install xlwt

In [ ]:
test.to_excel('/content/drive/MyDrive/빅콘테스트/02_평가데이터/최종제출.xlsx', sheet_name='Sheet1', index=False)